<?php header('Content-type: text/calendar; charset=utf-8'); ?>
<?php header('Content-disposition: attachment; filename="'.$title.'"'); ?>
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//JESSE OVERRIGHT//<?= $title ?>//EN
X-WR-CALNAME:<?= $title ?> 
X-WR-TIMEZONE:America/Chicago
BEGIN:VTIMEZONE
TZID:US/Central
X-LIC-LOCATION:America/Chicago
BEGIN:DAYLIGHT
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
TZNAME:CDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
TZNAME:CST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
